// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     organization.avsc
 *     school.avsc
 *     user.avsc
 *     class.avsc
 *     organization_membership.avsc
 *     school_membership.avsc
 *     class_roster.avsc
 *     s3filecreated.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ClassRosterPayload struct {
	Name string `json:"name"`

	Class_uuid string `json:"class_uuid"`

	User_uuid string `json:"user_uuid"`

	Participating_as string `json:"participating_as"`
}

const ClassRosterPayloadAvroCRC64Fingerprint = "\n\xfa\xac̆K1\x91"

func NewClassRosterPayload() ClassRosterPayload {
	r := ClassRosterPayload{}
	return r
}

func DeserializeClassRosterPayload(r io.Reader) (ClassRosterPayload, error) {
	t := NewClassRosterPayload()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeClassRosterPayloadFromSchema(r io.Reader, schema string) (ClassRosterPayload, error) {
	t := NewClassRosterPayload()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeClassRosterPayload(r ClassRosterPayload, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Name, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Class_uuid, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.User_uuid, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Participating_as, w)
	if err != nil {
		return err
	}
	return err
}

func (r ClassRosterPayload) Serialize(w io.Writer) error {
	return writeClassRosterPayload(r, w)
}

func (r ClassRosterPayload) Schema() string {
	return "{\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"class_uuid\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"user_uuid\",\"type\":\"string\"},{\"name\":\"participating_as\",\"type\":\"string\"}],\"name\":\"com.kidsloop.onboarding.ClassRosterPayload\",\"type\":\"record\"}"
}

func (r ClassRosterPayload) SchemaName() string {
	return "com.kidsloop.onboarding.ClassRosterPayload"
}

func (_ ClassRosterPayload) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ClassRosterPayload) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ClassRosterPayload) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ClassRosterPayload) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ClassRosterPayload) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ClassRosterPayload) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ClassRosterPayload) SetString(v string)   { panic("Unsupported operation") }
func (_ ClassRosterPayload) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ClassRosterPayload) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Name}

		return w

	case 1:
		w := types.String{Target: &r.Class_uuid}

		return w

	case 2:
		w := types.String{Target: &r.User_uuid}

		return w

	case 3:
		w := types.String{Target: &r.Participating_as}

		return w

	}
	panic("Unknown field index")
}

func (r *ClassRosterPayload) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ClassRosterPayload) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ClassRosterPayload) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ClassRosterPayload) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ClassRosterPayload) HintSize(int)                     { panic("Unsupported operation") }
func (_ ClassRosterPayload) Finalize()                        {}

func (_ ClassRosterPayload) AvroCRC64Fingerprint() []byte {
	return []byte(ClassRosterPayloadAvroCRC64Fingerprint)
}

func (r ClassRosterPayload) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["name"], err = json.Marshal(r.Name)
	if err != nil {
		return nil, err
	}
	output["class_uuid"], err = json.Marshal(r.Class_uuid)
	if err != nil {
		return nil, err
	}
	output["user_uuid"], err = json.Marshal(r.User_uuid)
	if err != nil {
		return nil, err
	}
	output["participating_as"], err = json.Marshal(r.Participating_as)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ClassRosterPayload) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["name"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Name); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for name")
	}
	val = func() json.RawMessage {
		if v, ok := fields["class_uuid"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Class_uuid); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for class_uuid")
	}
	val = func() json.RawMessage {
		if v, ok := fields["user_uuid"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.User_uuid); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for user_uuid")
	}
	val = func() json.RawMessage {
		if v, ok := fields["participating_as"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Participating_as); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for participating_as")
	}
	return nil
}
