// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     organization.avsc
 *     school.avsc
 *     user.avsc
 *     class.avsc
 *     organization_membership.avsc
 *     class_details.avsc
 *     class_roster.avsc
 *     school_membership.avsc
 *     s3filecreated.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ClassDetails struct {
	Payload ClassDetailsPayload `json:"payload"`

	Metadata ClassDetailsMetadata `json:"metadata"`
}

const ClassDetailsAvroCRC64Fingerprint = "\xe8\x1c\xe5\x84\xe4f\x8e\xac"

func NewClassDetails() ClassDetails {
	r := ClassDetails{}
	r.Payload = NewClassDetailsPayload()

	r.Metadata = NewClassDetailsMetadata()

	return r
}

func DeserializeClassDetails(r io.Reader) (ClassDetails, error) {
	t := NewClassDetails()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeClassDetailsFromSchema(r io.Reader, schema string) (ClassDetails, error) {
	t := NewClassDetails()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeClassDetails(r ClassDetails, w io.Writer) error {
	var err error
	err = writeClassDetailsPayload(r.Payload, w)
	if err != nil {
		return err
	}
	err = writeClassDetailsMetadata(r.Metadata, w)
	if err != nil {
		return err
	}
	return err
}

func (r ClassDetails) Serialize(w io.Writer) error {
	return writeClassDetails(r, w)
}

func (r ClassDetails) Schema() string {
	return "{\"fields\":[{\"name\":\"payload\",\"type\":{\"fields\":[{\"logicalType\":\"uuid\",\"name\":\"class_uuid\",\"type\":\"string\"},{\"default\":null,\"logicalType\":\"uuid\",\"name\":\"school_uuid\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"program_uuids\",\"type\":[\"null\",{\"items\":\"string\",\"type\":\"array\"}]},{\"default\":null,\"name\":\"subject_uuids\",\"type\":[\"null\",{\"items\":\"string\",\"type\":\"array\"}]},{\"default\":null,\"name\":\"grade_uuids\",\"type\":[\"null\",{\"items\":\"string\",\"type\":\"array\"}]},{\"default\":null,\"name\":\"age_range_uuids\",\"type\":[\"null\",{\"items\":\"string\",\"type\":\"array\"}]},{\"default\":null,\"logicalType\":\"uuid\",\"name\":\"academic_term_uuid\",\"type\":[\"null\",\"string\"]}],\"name\":\"ClassDetailsPayload\",\"type\":\"record\"}},{\"name\":\"metadata\",\"type\":{\"fields\":[{\"name\":\"origin_application\",\"type\":\"string\"},{\"name\":\"region\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"tracking_uuid\",\"type\":\"string\"}],\"name\":\"ClassDetailsMetadata\",\"type\":\"record\"}}],\"name\":\"com.kidsloop.onboarding.ClassDetails\",\"type\":\"record\"}"
}

func (r ClassDetails) SchemaName() string {
	return "com.kidsloop.onboarding.ClassDetails"
}

func (_ ClassDetails) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ClassDetails) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ClassDetails) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ClassDetails) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ClassDetails) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ClassDetails) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ClassDetails) SetString(v string)   { panic("Unsupported operation") }
func (_ ClassDetails) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ClassDetails) Get(i int) types.Field {
	switch i {
	case 0:
		r.Payload = NewClassDetailsPayload()

		w := types.Record{Target: &r.Payload}

		return w

	case 1:
		r.Metadata = NewClassDetailsMetadata()

		w := types.Record{Target: &r.Metadata}

		return w

	}
	panic("Unknown field index")
}

func (r *ClassDetails) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ClassDetails) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ClassDetails) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ClassDetails) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ClassDetails) HintSize(int)                     { panic("Unsupported operation") }
func (_ ClassDetails) Finalize()                        {}

func (_ ClassDetails) AvroCRC64Fingerprint() []byte {
	return []byte(ClassDetailsAvroCRC64Fingerprint)
}

func (r ClassDetails) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["payload"], err = json.Marshal(r.Payload)
	if err != nil {
		return nil, err
	}
	output["metadata"], err = json.Marshal(r.Metadata)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ClassDetails) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["payload"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Payload); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for payload")
	}
	val = func() json.RawMessage {
		if v, ok := fields["metadata"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Metadata); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for metadata")
	}
	return nil
}
