// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     organization.avsc
 *     school.avsc
 *     user.avsc
 *     s3filecreated.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type GenderType int32

const (
	GenderTypeMALE   GenderType = 0
	GenderTypeFEMALE GenderType = 1
)

func (e GenderType) String() string {
	switch e {
	case GenderTypeMALE:
		return "MALE"
	case GenderTypeFEMALE:
		return "FEMALE"
	}
	return "unknown"
}

func writeGenderType(r GenderType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewGenderTypeValue(raw string) (r GenderType, err error) {
	switch raw {
	case "MALE":
		return GenderTypeMALE, nil
	case "FEMALE":
		return GenderTypeFEMALE, nil
	}

	return -1, fmt.Errorf("invalid value for GenderType: '%s'", raw)

}

func (b GenderType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *GenderType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewGenderTypeValue(stringVal)
	*b = val
	return err
}

type GenderTypeWrapper struct {
	Target *GenderType
}

func (b GenderTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b GenderTypeWrapper) SetInt(v int32) {
	*(b.Target) = GenderType(v)
}

func (b GenderTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b GenderTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b GenderTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b GenderTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b GenderTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b GenderTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b GenderTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b GenderTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b GenderTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b GenderTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b GenderTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b GenderTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b GenderTypeWrapper) Finalize() {}
