// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     organization.avsc
 *     school.avsc
 *     user.avsc
 *     class.avsc
 *     organization_membership.avsc
 *     class_details.avsc
 *     school_membership.avsc
 *     s3filecreated.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type OrganizationMembership struct {
	Payload OrganizationMembershipPayload `json:"payload"`

	Metadata OrganizationMembershipMetadata `json:"metadata"`
}

const OrganizationMembershipAvroCRC64Fingerprint = "\xee\xc0\x8f>|h}G"

func NewOrganizationMembership() OrganizationMembership {
	r := OrganizationMembership{}
	r.Payload = NewOrganizationMembershipPayload()

	r.Metadata = NewOrganizationMembershipMetadata()

	return r
}

func DeserializeOrganizationMembership(r io.Reader) (OrganizationMembership, error) {
	t := NewOrganizationMembership()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeOrganizationMembershipFromSchema(r io.Reader, schema string) (OrganizationMembership, error) {
	t := NewOrganizationMembership()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeOrganizationMembership(r OrganizationMembership, w io.Writer) error {
	var err error
	err = writeOrganizationMembershipPayload(r.Payload, w)
	if err != nil {
		return err
	}
	err = writeOrganizationMembershipMetadata(r.Metadata, w)
	if err != nil {
		return err
	}
	return err
}

func (r OrganizationMembership) Serialize(w io.Writer) error {
	return writeOrganizationMembership(r, w)
}

func (r OrganizationMembership) Schema() string {
	return "{\"fields\":[{\"name\":\"payload\",\"type\":{\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"organization_uuid\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"user_uuid\",\"type\":\"string\"},{\"name\":\"organization_role_uuids\",\"type\":{\"items\":{\"logicalType\":\"uuid\",\"name\":\"OrganizationRoleUuid\",\"type\":\"string\"},\"type\":\"array\"}}],\"name\":\"OrganizationMembershipPayload\",\"type\":\"record\"}},{\"name\":\"metadata\",\"type\":{\"fields\":[{\"name\":\"origin_application\",\"type\":\"string\"},{\"name\":\"region\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"tracking_uuid\",\"type\":\"string\"}],\"name\":\"OrganizationMembershipMetadata\",\"type\":\"record\"}}],\"name\":\"com.kidsloop.onboarding.OrganizationMembership\",\"type\":\"record\"}"
}

func (r OrganizationMembership) SchemaName() string {
	return "com.kidsloop.onboarding.OrganizationMembership"
}

func (_ OrganizationMembership) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ OrganizationMembership) SetInt(v int32)       { panic("Unsupported operation") }
func (_ OrganizationMembership) SetLong(v int64)      { panic("Unsupported operation") }
func (_ OrganizationMembership) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ OrganizationMembership) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ OrganizationMembership) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ OrganizationMembership) SetString(v string)   { panic("Unsupported operation") }
func (_ OrganizationMembership) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *OrganizationMembership) Get(i int) types.Field {
	switch i {
	case 0:
		r.Payload = NewOrganizationMembershipPayload()

		w := types.Record{Target: &r.Payload}

		return w

	case 1:
		r.Metadata = NewOrganizationMembershipMetadata()

		w := types.Record{Target: &r.Metadata}

		return w

	}
	panic("Unknown field index")
}

func (r *OrganizationMembership) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *OrganizationMembership) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ OrganizationMembership) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ OrganizationMembership) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ OrganizationMembership) HintSize(int)                     { panic("Unsupported operation") }
func (_ OrganizationMembership) Finalize()                        {}

func (_ OrganizationMembership) AvroCRC64Fingerprint() []byte {
	return []byte(OrganizationMembershipAvroCRC64Fingerprint)
}

func (r OrganizationMembership) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["payload"], err = json.Marshal(r.Payload)
	if err != nil {
		return nil, err
	}
	output["metadata"], err = json.Marshal(r.Metadata)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *OrganizationMembership) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["payload"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Payload); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for payload")
	}
	val = func() json.RawMessage {
		if v, ok := fields["metadata"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Metadata); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for metadata")
	}
	return nil
}
