// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     organization.avsc
 *     school.avsc
 *     s3filecreated.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type S3FileCreated struct {
	Payload S3FileCreatedPayload `json:"payload"`

	Metadata S3FileCreatedMetadata `json:"metadata"`
}

const S3FileCreatedAvroCRC64Fingerprint = "Ӯt\xd1\x11\x97:o"

func NewS3FileCreated() S3FileCreated {
	r := S3FileCreated{}
	r.Payload = NewS3FileCreatedPayload()

	r.Metadata = NewS3FileCreatedMetadata()

	return r
}

func DeserializeS3FileCreated(r io.Reader) (S3FileCreated, error) {
	t := NewS3FileCreated()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeS3FileCreatedFromSchema(r io.Reader, schema string) (S3FileCreated, error) {
	t := NewS3FileCreated()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeS3FileCreated(r S3FileCreated, w io.Writer) error {
	var err error
	err = writeS3FileCreatedPayload(r.Payload, w)
	if err != nil {
		return err
	}
	err = writeS3FileCreatedMetadata(r.Metadata, w)
	if err != nil {
		return err
	}
	return err
}

func (r S3FileCreated) Serialize(w io.Writer) error {
	return writeS3FileCreated(r, w)
}

func (r S3FileCreated) Schema() string {
	return "{\"fields\":[{\"name\":\"payload\",\"type\":{\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"aws_region\",\"type\":\"string\"},{\"name\":\"bucket_name\",\"type\":\"string\"},{\"name\":\"content_length\",\"type\":\"long\"},{\"name\":\"content_type\",\"type\":\"string\"},{\"name\":\"operation_type\",\"type\":\"string\"}],\"name\":\"S3FileCreatedPayload\",\"type\":\"record\"}},{\"name\":\"metadata\",\"type\":{\"fields\":[{\"name\":\"origin_application\",\"type\":\"string\"},{\"name\":\"region\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"tracking_id\",\"type\":\"string\"}],\"name\":\"S3FileCreatedMetadata\",\"type\":\"record\"}}],\"name\":\"com.kidsloop.onboarding.S3FileCreated\",\"type\":\"record\"}"
}

func (r S3FileCreated) SchemaName() string {
	return "com.kidsloop.onboarding.S3FileCreated"
}

func (_ S3FileCreated) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ S3FileCreated) SetInt(v int32)       { panic("Unsupported operation") }
func (_ S3FileCreated) SetLong(v int64)      { panic("Unsupported operation") }
func (_ S3FileCreated) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ S3FileCreated) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ S3FileCreated) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ S3FileCreated) SetString(v string)   { panic("Unsupported operation") }
func (_ S3FileCreated) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *S3FileCreated) Get(i int) types.Field {
	switch i {
	case 0:
		r.Payload = NewS3FileCreatedPayload()

		w := types.Record{Target: &r.Payload}

		return w

	case 1:
		r.Metadata = NewS3FileCreatedMetadata()

		w := types.Record{Target: &r.Metadata}

		return w

	}
	panic("Unknown field index")
}

func (r *S3FileCreated) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *S3FileCreated) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ S3FileCreated) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ S3FileCreated) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ S3FileCreated) HintSize(int)                     { panic("Unsupported operation") }
func (_ S3FileCreated) Finalize()                        {}

func (_ S3FileCreated) AvroCRC64Fingerprint() []byte {
	return []byte(S3FileCreatedAvroCRC64Fingerprint)
}

func (r S3FileCreated) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["payload"], err = json.Marshal(r.Payload)
	if err != nil {
		return nil, err
	}
	output["metadata"], err = json.Marshal(r.Metadata)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *S3FileCreated) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["payload"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Payload); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for payload")
	}
	val = func() json.RawMessage {
		if v, ok := fields["metadata"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Metadata); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for metadata")
	}
	return nil
}
