// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     organization.avsc
 *     school.avsc
 *     user.avsc
 *     class.avsc
 *     organization_membership.avsc
 *     class_details.avsc
 *     class_roster.avsc
 *     school_membership.avsc
 *     s3filecreated.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type SchoolMembership struct {
	Payload SchoolMembershipPayload `json:"payload"`

	Metadata SchoolMembershipMetadata `json:"metadata"`
}

const SchoolMembershipAvroCRC64Fingerprint = "\xe1W\x1a\xd1!(\x9c\xa4"

func NewSchoolMembership() SchoolMembership {
	r := SchoolMembership{}
	r.Payload = NewSchoolMembershipPayload()

	r.Metadata = NewSchoolMembershipMetadata()

	return r
}

func DeserializeSchoolMembership(r io.Reader) (SchoolMembership, error) {
	t := NewSchoolMembership()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeSchoolMembershipFromSchema(r io.Reader, schema string) (SchoolMembership, error) {
	t := NewSchoolMembership()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeSchoolMembership(r SchoolMembership, w io.Writer) error {
	var err error
	err = writeSchoolMembershipPayload(r.Payload, w)
	if err != nil {
		return err
	}
	err = writeSchoolMembershipMetadata(r.Metadata, w)
	if err != nil {
		return err
	}
	return err
}

func (r SchoolMembership) Serialize(w io.Writer) error {
	return writeSchoolMembership(r, w)
}

func (r SchoolMembership) Schema() string {
	return "{\"fields\":[{\"name\":\"payload\",\"type\":{\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"school_uuid\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"user_uuid\",\"type\":\"string\"}],\"name\":\"SchoolMembershipPayload\",\"type\":\"record\"}},{\"name\":\"metadata\",\"type\":{\"fields\":[{\"name\":\"origin_application\",\"type\":\"string\"},{\"name\":\"region\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"tracking_uuid\",\"type\":\"string\"}],\"name\":\"SchoolMembershipMetadata\",\"type\":\"record\"}}],\"name\":\"com.kidsloop.onboarding.SchoolMembership\",\"type\":\"record\"}"
}

func (r SchoolMembership) SchemaName() string {
	return "com.kidsloop.onboarding.SchoolMembership"
}

func (_ SchoolMembership) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ SchoolMembership) SetInt(v int32)       { panic("Unsupported operation") }
func (_ SchoolMembership) SetLong(v int64)      { panic("Unsupported operation") }
func (_ SchoolMembership) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ SchoolMembership) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ SchoolMembership) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ SchoolMembership) SetString(v string)   { panic("Unsupported operation") }
func (_ SchoolMembership) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *SchoolMembership) Get(i int) types.Field {
	switch i {
	case 0:
		r.Payload = NewSchoolMembershipPayload()

		w := types.Record{Target: &r.Payload}

		return w

	case 1:
		r.Metadata = NewSchoolMembershipMetadata()

		w := types.Record{Target: &r.Metadata}

		return w

	}
	panic("Unknown field index")
}

func (r *SchoolMembership) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *SchoolMembership) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ SchoolMembership) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ SchoolMembership) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ SchoolMembership) HintSize(int)                     { panic("Unsupported operation") }
func (_ SchoolMembership) Finalize()                        {}

func (_ SchoolMembership) AvroCRC64Fingerprint() []byte {
	return []byte(SchoolMembershipAvroCRC64Fingerprint)
}

func (r SchoolMembership) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["payload"], err = json.Marshal(r.Payload)
	if err != nil {
		return nil, err
	}
	output["metadata"], err = json.Marshal(r.Metadata)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *SchoolMembership) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["payload"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Payload); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for payload")
	}
	val = func() json.RawMessage {
		if v, ok := fields["metadata"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Metadata); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for metadata")
	}
	return nil
}
