// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     organization.avsc
 *     s3filecreated.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type OrganizationPayload struct {
	Organization_name string `json:"organization_name"`

	Guid string `json:"guid"`
}

const OrganizationPayloadAvroCRC64Fingerprint = "p\x8do\xadD\x1b\xdaC"

func NewOrganizationPayload() OrganizationPayload {
	r := OrganizationPayload{}
	return r
}

func DeserializeOrganizationPayload(r io.Reader) (OrganizationPayload, error) {
	t := NewOrganizationPayload()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeOrganizationPayloadFromSchema(r io.Reader, schema string) (OrganizationPayload, error) {
	t := NewOrganizationPayload()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeOrganizationPayload(r OrganizationPayload, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Organization_name, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Guid, w)
	if err != nil {
		return err
	}
	return err
}

func (r OrganizationPayload) Serialize(w io.Writer) error {
	return writeOrganizationPayload(r, w)
}

func (r OrganizationPayload) Schema() string {
	return "{\"fields\":[{\"name\":\"organization_name\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"guid\",\"type\":\"string\"}],\"name\":\"com.kidsloop.onboarding.OrganizationPayload\",\"type\":\"record\"}"
}

func (r OrganizationPayload) SchemaName() string {
	return "com.kidsloop.onboarding.OrganizationPayload"
}

func (_ OrganizationPayload) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ OrganizationPayload) SetInt(v int32)       { panic("Unsupported operation") }
func (_ OrganizationPayload) SetLong(v int64)      { panic("Unsupported operation") }
func (_ OrganizationPayload) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ OrganizationPayload) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ OrganizationPayload) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ OrganizationPayload) SetString(v string)   { panic("Unsupported operation") }
func (_ OrganizationPayload) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *OrganizationPayload) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Organization_name}

		return w

	case 1:
		w := types.String{Target: &r.Guid}

		return w

	}
	panic("Unknown field index")
}

func (r *OrganizationPayload) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *OrganizationPayload) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ OrganizationPayload) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ OrganizationPayload) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ OrganizationPayload) HintSize(int)                     { panic("Unsupported operation") }
func (_ OrganizationPayload) Finalize()                        {}

func (_ OrganizationPayload) AvroCRC64Fingerprint() []byte {
	return []byte(OrganizationPayloadAvroCRC64Fingerprint)
}

func (r OrganizationPayload) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["organization_name"], err = json.Marshal(r.Organization_name)
	if err != nil {
		return nil, err
	}
	output["guid"], err = json.Marshal(r.Guid)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *OrganizationPayload) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["organization_name"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Organization_name); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for organization_name")
	}
	val = func() json.RawMessage {
		if v, ok := fields["guid"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Guid); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for guid")
	}
	return nil
}
