// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: csvfile.proto

package csvfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_ORGANIZATION Type = 0
	Type_SCHOOL       Type = 1
	Type_CLASS        Type = 2
	Type_USER         Type = 3
	Type_ROLE         Type = 4
	Type_PROGRAM      Type = 5
	Type_UNKNOWN      Type = 6
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "ORGANIZATION",
		1: "SCHOOL",
		2: "CLASS",
		3: "USER",
		4: "ROLE",
		5: "PROGRAM",
		6: "UNKNOWN",
	}
	Type_value = map[string]int32{
		"ORGANIZATION": 0,
		"SCHOOL":       1,
		"CLASS":        2,
		"USER":         3,
		"ROLE":         4,
		"PROGRAM":      5,
		"UNKNOWN":      6,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_csvfile_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_csvfile_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_csvfile_proto_rawDescGZIP(), []int{0}
}

type CsvFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CsvFile) Reset() {
	*x = CsvFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csvfile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsvFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsvFile) ProtoMessage() {}

func (x *CsvFile) ProtoReflect() protoreflect.Message {
	mi := &file_csvfile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsvFile.ProtoReflect.Descriptor instead.
func (*CsvFile) Descriptor() ([]byte, []int) {
	return file_csvfile_proto_rawDescGZIP(), []int{0}
}

func (x *CsvFile) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CsvFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CsvFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    Type     `protobuf:"varint,1,opt,name=type,proto3,enum=protos.csvfile.Type" json:"type,omitempty"`
	Csvfile *CsvFile `protobuf:"bytes,2,opt,name=csvfile,proto3" json:"csvfile,omitempty"`
}

func (x *CsvFileRequest) Reset() {
	*x = CsvFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csvfile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsvFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsvFileRequest) ProtoMessage() {}

func (x *CsvFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csvfile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsvFileRequest.ProtoReflect.Descriptor instead.
func (*CsvFileRequest) Descriptor() ([]byte, []int) {
	return file_csvfile_proto_rawDescGZIP(), []int{1}
}

func (x *CsvFileRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_ORGANIZATION
}

func (x *CsvFileRequest) GetCsvfile() *CsvFile {
	if x != nil {
		return x.Csvfile
	}
	return nil
}

type CsvFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool        `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Errors  []*CsvError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *CsvFileResponse) Reset() {
	*x = CsvFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csvfile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsvFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsvFileResponse) ProtoMessage() {}

func (x *CsvFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csvfile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsvFileResponse.ProtoReflect.Descriptor instead.
func (*CsvFileResponse) Descriptor() ([]byte, []int) {
	return file_csvfile_proto_rawDescGZIP(), []int{2}
}

func (x *CsvFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CsvFileResponse) GetErrors() []*CsvError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CsvError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId  string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Message []string `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *CsvError) Reset() {
	*x = CsvError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csvfile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsvError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsvError) ProtoMessage() {}

func (x *CsvError) ProtoReflect() protoreflect.Message {
	mi := &file_csvfile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsvError.ProtoReflect.Descriptor instead.
func (*CsvError) Descriptor() ([]byte, []int) {
	return file_csvfile_proto_rawDescGZIP(), []int{3}
}

func (x *CsvError) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CsvError) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_csvfile_proto protoreflect.FileDescriptor

var file_csvfile_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x73, 0x76, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x73, 0x76, 0x66, 0x69, 0x6c, 0x65, 0x22,
	0x36, 0x0a, 0x07, 0x43, 0x73, 0x76, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x6d, 0x0a, 0x0e, 0x43, 0x73, 0x76, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x63, 0x73, 0x76, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x73, 0x76, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x73,
	0x76, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x73, 0x76, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x63,
	0x73, 0x76, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x5d, 0x0a, 0x0f, 0x43, 0x73, 0x76, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x73, 0x76,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x73, 0x76, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x3d, 0x0a, 0x08, 0x43, 0x73, 0x76, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2a, 0x5d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x4f, 0x52, 0x47, 0x41, 0x4e, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x43, 0x48, 0x4f, 0x4f, 0x4c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c,
	0x41, 0x53, 0x53, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f,
	0x47, 0x52, 0x41, 0x4d, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x06, 0x32, 0x62, 0x0a, 0x0e, 0x43, 0x73, 0x76, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x09, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x43,
	0x53, 0x56, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x73, 0x76, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x43, 0x73, 0x76, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x73, 0x76, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x43, 0x73, 0x76, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x73, 0x76, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_csvfile_proto_rawDescOnce sync.Once
	file_csvfile_proto_rawDescData = file_csvfile_proto_rawDesc
)

func file_csvfile_proto_rawDescGZIP() []byte {
	file_csvfile_proto_rawDescOnce.Do(func() {
		file_csvfile_proto_rawDescData = protoimpl.X.CompressGZIP(file_csvfile_proto_rawDescData)
	})
	return file_csvfile_proto_rawDescData
}

var file_csvfile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_csvfile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_csvfile_proto_goTypes = []interface{}{
	(Type)(0),               // 0: protos.csvfile.Type
	(*CsvFile)(nil),         // 1: protos.csvfile.CsvFile
	(*CsvFileRequest)(nil),  // 2: protos.csvfile.CsvFileRequest
	(*CsvFileResponse)(nil), // 3: protos.csvfile.CsvFileResponse
	(*CsvError)(nil),        // 4: protos.csvfile.CsvError
}
var file_csvfile_proto_depIdxs = []int32{
	0, // 0: protos.csvfile.CsvFileRequest.type:type_name -> protos.csvfile.Type
	1, // 1: protos.csvfile.CsvFileRequest.csvfile:type_name -> protos.csvfile.CsvFile
	4, // 2: protos.csvfile.CsvFileResponse.errors:type_name -> protos.csvfile.CsvError
	2, // 3: protos.csvfile.CsvFileService.IngestCSV:input_type -> protos.csvfile.CsvFileRequest
	3, // 4: protos.csvfile.CsvFileService.IngestCSV:output_type -> protos.csvfile.CsvFileResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_csvfile_proto_init() }
func file_csvfile_proto_init() {
	if File_csvfile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csvfile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsvFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csvfile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsvFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csvfile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsvFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csvfile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsvError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csvfile_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csvfile_proto_goTypes,
		DependencyIndexes: file_csvfile_proto_depIdxs,
		EnumInfos:         file_csvfile_proto_enumTypes,
		MessageInfos:      file_csvfile_proto_msgTypes,
	}.Build()
	File_csvfile_proto = out.File
	file_csvfile_proto_rawDesc = nil
	file_csvfile_proto_goTypes = nil
	file_csvfile_proto_depIdxs = nil
}
